version: "3"

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:7.0
    volumes:
      - poke-vol:/data/db
    ports:
      - 27018:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']

volumes:
  poke-vol:
    external: false