version: '3'

services:
  db:
    container_name: postgres-db
    image: postgres:16.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    container_name: pgAdmin4
    depends_on:
      - db
    image: dpage/pgadmin4:8.1
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

# volumes:
#   postgres-db:
#     external: true